### ISSUE TITLE
Mirror account polishing

### ISSUE THREAD

**Issue by burningtree** [web3privacy/core#12]
- [ ] buy and use ENS domain web3privacy/w3pn-core#4
- [x] rename "Web3privacy now" -> "Web3Privacy Now"
- [x] link Twitter account
- [x] change avatar to logo
- [ ] visual for profile header @coinmandeer ([1697px x 360px](https://support.mirror.xyz/hc/en-us/articles/10908171916436-What-dimensions-and-file-formats-are-best-for-images-on-Mirror-))

**Comment by Msiusko** [comment]
Done my part.

Waiting for 
- Coin's pic
- ENS

**Comment by burningtree** [comment]
@coinmandeer Please check this.
