### ISSUE TITLE
Situation around Explorer

### ISSUE THREAD

**Issue by burningtree** [web3privacy/core#36]
The Explorer project had only one simple goal and that was to replace the original [Markdown database](https://github.com/web3privacy/web3privacy/blob/main/README.md) that Mykola created. After more than 4 months it is clear that it has failed to meet that simple goal and there are **no prospects of that happening anytime soon**.

So I would like to open the question of what to do about it, and whether it makes sense to continue with this project at all. Dozens of hours of work have been spent on this, and I would really dont want to lose another our energy by continuing on a project that doesn't work.

Probably the biggest problem this project brings is the duplication of work, with information in multiple places and the complete lack of `explorer-data` being maintained or moved forward. There is no concept for data maintaining and basically no one is driving it and no one cares much about it. Instead of addressing this, we are preparing some overcomplicated json schemas that nobody using.

This leads us to another problem with Explorer, and that is a general lack of leadership and direction. The whole thing is only being pushed forward because it was started in a hurry and in a rush at the ETHRome hackathon, and now everyone believes it will drive itself. It won't.

I think it's time to admit that this project just didn't work and scratch it.

I understand that many of you will resist this, but from my perspective I really don't see any other way out. Because if we continue to do this, we're just going to waste a lot of time, energy and who knows what else, and it could have much worse consequences than it has had up to now.

## Related issues & PRs

- web3privacy/web#9

**Comment by aspiers** [comment]
Please could you clarify for the benefit of newcomers here such as myself: why was it considered a failure, and why does it seem there are no prospects of fixing that?  E.g. was it the lack of a user-friendly UI for updating the JSON?

**Comment by aspiers** [comment]
Also, while this is in limbo, it would be nice to add a warning to https://explorer.web3privacy.info/ about that, to avoid people wasting time compiling the JSON for their project.  I had just started writing the JSON for my project, and then started wondering why the explorer wasn't linked from https://web3privacy.info/.  I only found this by search the website repo for `explorer`, and doing `git blame` on the commented navigation link.  I could have easily wasted several hours on the JSON if I hadn't done this first.

**Comment by burningtree** [comment]
> Please could you clarify for the benefit of newcomers here such as myself: why was it considered a failure, and why does it seem there are no prospects of fixing that? E.g. was it the lack of a user-friendly UI for updating the JSON?

I wrote it here as my personal opinion. IMO The problem isn't the dataset itself, or the lack of some tools - it's the lack of any leadership/project management/direction/competence around this project (e.g. - nobody really cares about this project).

I would have liked to see some warnings as well - I have been calling for a similar warning from the beginning. Unfortunately, the W3PN core team thinks this project is working great and that no such warnings are needed - even the removal from the W3PN homepage was a big push on my part (I practically decided for others, as the author of the site). 

Explorer is a big marketing bait and nobody wants to talk about negative things.

I have no other explanation for the fact that after 7 months it's still totally unusable and the UI gives misleading information (all projects have "Anonymous" team flag, which is nonsense).

---

Note: I am no longer a member of the W3PN core team (also because of these issues).

**Comment by burningtree** [comment]
Personally, I don't recommend anyone to waste time adding data to the explorer-data repository.

1. No leadership
1. No direction
1. No developers (only cooperation with an external company supervised by a graphic designer)

Why these things don't work is a slightly more complex question related to the marketing nature of Web3Privacy Now. In short - Saying something doesn't work is not good for marketing.

I don't like the W3PN core team is still promoting this, it seems a bit dishonest and I don't want to be a part of it.

<img width="597" alt="Screenshot" src="https://github.com/web3privacy/core/assets/67269/1a119515-f84c-4ffc-94d4-41a4c534c144">

**Comment by aspiers** [comment]
Thanks for the honest info - this tweet was how I found out about the explorer, and indeed it does seem a bit disappointing that there's not a clear strategy on how to resolve this.  A reply from someone still in the project would be helpful here; it's better to talk about the issue openly and try to resolve it.
