### ISSUE TITLE
W3PN Slogan(s)

### ISSUE THREAD

**Issue by burningtree** [web3privacy/core#41]
It would be nice to have at least one [slogan](https://en.wikipedia.org/wiki/Slogan) (*a memorable motto or phrase*) that describes W3PN.

@Msiusko Let's go :)

**Comment by Msiusko** [comment]
Indeed + link it to visual symbol & maybe even a mascot for socials in the future

**Comment by Msiusko** [comment]
Indeed + link it to visual symbol & maybe even a mascot for socials in the future
