### ISSUE TITLE
Typefully for Twitter

### ISSUE THREAD

**Issue by burningtree** [web3privacy/core#7]
https://typefully.com/

**Comment by EclecticSamurai** [comment]
I used both typefully and [Buffer](https://buffer.com/) and find the latter a lot better.

**Comment by burningtree** [comment]
> I used both typefully and [Buffer](https://buffer.com/) and find the latter a lot better.

@EclecticSamurai Hmm. I tried to make trial account on Buffer and for me it seems to be very heavy and slow.

Can you please write some reasoning why you think its better than Typefully?
