### ISSUE TITLE
"brand" repo & docs

### ISSUE THREAD

**Issue by burningtree** [web3privacy/core#8]
- logos
- favicons
- other visuals

**Comment by coinmandeer** [comment]
[web3privacy-favicon.zip](https://github.com/web3privacy/w3pn-core/files/13319966/web3privacy-favicon.zip)

**Comment by burningtree** [comment]
Cool now we have files in repo
https://github.com/web3privacy/brand

Next step - make some documentation for that:
https://docs.web3privacy.info/brand/

cc @coinmandeer
